"
I am the package concerning SoccerML. SoccerML is a XML data format for soccer scenes.
Basically, the data consists of header information and a sequence of STSoccerFrame.  
By convention, a SoccerML file should have the extension “.socxml”.

I am responsable for reading and writing SoccerML files.
I also care for transformations from and to other file formats like 
- RoboCup logfiles
- Statistical input files
"
Class {
	#name : 'ManifestSoccerTheorySoccerML',
	#superclass : 'PackageManifest',
	#category : 'SoccerTheory-SoccerML-Manifest',
	#package : 'SoccerTheory-SoccerML',
	#tag : 'Manifest'
}
