"
I extract from a game source for both teams a STMatchEventExtract each. 
"
Class {
	#name : 'STMatchEventExtractor',
	#superclass : 'Object',
	#instVars : [
		'team1Extract',
		'team2Extract'
	],
	#category : 'SoccerTheory-Statistics',
	#package : 'SoccerTheory-Statistics'
}

{ #category : 'accessing' }
STMatchEventExtractor >> team1Extract [

	^ team1Extract
]

{ #category : 'accessing' }
STMatchEventExtractor >> team2Extract [

	^ team2Extract
]
